### ISSUE TITLE
App GIU photo

### ISSUE THREAD

**Issue by pgys** [liketohear/liketohear#4]
![Screenshot_GUI](https://user-images.githubusercontent.com/10296132/67571065-51d7ca00-f733-11e9-92dd-4f06c5e00a91.jpg)
![screenshot_App](https://user-images.githubusercontent.com/10296132/67571066-51d7ca00-f733-11e9-839c-4f6a4b2a5a14.jpg)

**Comment by TobiBruns** [comment]
@pgys Is this done? Could you close this issue?

**Comment by pgys** [comment]
Done
