### ISSUE TITLE
Installation #liketohear extensions

### ISSUE THREAD

**Issue by HHZZUUJH** [liketohear/liketohear#5]
**After the correct execution of:**

Install the #liketohear extensions and control app on your Raspberry Pi:
1.	Plug in your USB-stick (otherwise the app won't work)
2.	Connect your Raspberry Pi to the internet.
3.	Clone the liketohear-directory from github into the first layer of your Raspberry file system:
git clone https://github.com/liketohear/liketohear
4.	Navigate to the folder
cd liketohear/resources
5.	Execute install.sh (please note: DON'T execute as root, means do NOT use "sudo")
./install.sh
6.	Confirm restarting the Raspberry Pi

7.	Connect your device (eg smartphone, tablet, laptop) to the WLAN of the Raspberry Pi.

8.	Open your Browser and connect to the webapp by typing the URL into the address line:
http://172.24.1.1:8888

**I get the following error message:** 

(the WLAN with the SSID "openMHA-wifi" is available. Ping on 172.24.1.1 is successful, but a web page cannot be opened)

-bash: $‘ \r` :command not found
-bash: /home/pi/.bashrc: line 6: syntax error near unexpected token `$‘ in\r``)
`bash: /home/pi/.bashrc line 6 `case $- in

the .bashrc file in the /home/pi directory corresponds to the bashrc file in the liketohear/resources directory

**Comment by TobiBruns** [comment]
I will have a look at this tomorrow

**Comment by HHZZUUJH** [comment]
Thank you very much. 

 

In the meantime I will create a new SD-Card with raspbian-openMHA-2.0.img.xz

 

Von: TobiBruns <notifications@github.com> 
Gesendet: Donnerstag, 27. Februar 2020 16:55
An: liketohear/liketohear <liketohear@noreply.github.com>
Cc: Hhz <hns376@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [liketohear/liketohear] Installation #liketohear extensions (#5)

 

I will have a look at this tomorrow

**Comment by HHZZUUJH** [comment]
I will also create a new SD-Card with raspbian-openMHA-2.0.img.xz for safety reasons

**Comment by HHZZUUJH** [comment]
After rebuilding, the above error has disappeared.
But now this error occurs:

[JACKD] JackAudioDriver::ProcessGraphAsyncMaster: Process error
[JACKD] JackEngine::XRun: client = MHA was nor finished, state = Running

[COMMANDER] Error opening 'configuration/feedback1.bin'

ERROR abhang:input_1 not a valid port
ERROR abhang:input_2 not a valid port
ERROR abhang:input_3 not a valid port
ERROR abhang:input_4 not a valid port
ERROR abhang:output_1 not a valid port
ERROR abhang:output_2 not a valid port

**Comment by HHZZUUJH** [comment]
I'll rebuild the pre-amplifier again.

**Comment by HHZZUUJH** [comment]
The above mentioned error has now reappeared.
After the reinstallation this error did not occur.   I had copied only the directory hearingaid-prototype without internet connection. The rpi-utils were not yet installed. After executing the command ./install.sh the error is back.

-bash: $‘ \r` :command not found
-bash: /home/pi/.bashrc: line 6: syntax error near unexpected token `$‘ in\r``)
`bash: /home/pi/.bashrc line 6 `case $- in

**Comment by HHZZUUJH** [comment]
The bug has been fixed.

**Comment by TobiBruns** [comment]
Sounds good! What was the solution to the problem?

**Comment by HHZZUUJH** [comment]
The solution was:

I had liketohear installed via a USB stick:

sudo mkdir /media/usbstick
sudo blkid -o list -w /dev/null
sudo mount -t vfat -o utf8,uid=pi,gid=pi,noatime /dev/sda1 /media/usbstick
cp -r /media/usbstick/liketohear /home/pi
cd /home/pi/lieketokear/ressources
./install.sh

this was not suitable.

has worked:

git clone https://github.com/liketohear/liketohear
./install.sh

**Comment by TobiBruns** [comment]
Copying via USB stick from windows unfortunately changes the execution rights of scripts and programs
