### ISSUE TITLE
how can the entries in the log file be evaluated?

### ISSUE THREAD

**Issue by HHZZUUJH** [liketohear/liketohear#9]
Example entry:

{"msg": "# RMS level in dB\n# vector<float> (monitor)\n[8.61453152 8.17349434 8.40927029 13.718174 12.8025684 21.3251095 10.7581635 8.51107693 11.8325844 12.006958 13.2003031 19.5938225]\n(MHA:success)\n", "userid": "abc", "data": [], "date": "Sun Mar  8 10:28:01 2020"}

**Comment by TobiBruns** [comment]
This is a json formatted string.

msg: contains the output from openMHA. Scripts for statistical evauation of these logs will be added in future releases.

 We are currently working on scripts for automatic statistical analysis on the log files. Will be included in future releases.

**Comment by TobiBruns** [comment]
tools/read_log.py is a very simple script for reading the logs

**Comment by liketohear** [comment]
Hi

create an accound at Jupyter notebook and fork the ai-project to  
evaluate the log file:
https://notebooks.ai/peggy/liketohear-ai-f671d451

If you have problems, I recommend to join my workshop April 4th in Berlin:
https://www.eventbrite.de/e/liketohear-workshop-for-open-source-hearing-devices-tickets-98613873751

Good luck, have fun
Peggy


Quoting Hhz <notifications@github.com>:

> Example entry:
>
> {"msg": "# RMS level in dB\n# vector<float> (monitor)\n[8.61453152  
> 8.17349434 8.40927029 13.718174 12.8025684 21.3251095 10.7581635  
> 8.51107693 11.8325844 12.006958 13.2003031  
> 19.5938225]\n(MHA:success)\n", "userid": "abc", "data": [], "date":  
> "Sun Mar  8 10:28:01 2020"}
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/liketohear/liketohear/issues/9


-- 
Dipl. Inf. Peggy Yvonne Sylopp

Citizen Science Project Manager "Hear How You Like To Hear"

https://twitter.com/like_to_hear
https://www.instagram.com/liketohear/
https://www.facebook.com/Like_to_hear

Fraunhofer Institute for Digital Media Technology IDMT
Project Group Hearing, Speech and Audio Technology
Haus des Hörens
Marie-Curie-Strasse 2
26129 Oldenburg, Germany

Tel.    +49 441 2172 433
Mobile  +49 157 5360 1070

**Comment by liketohear** [comment]
... Correction: April 3rd,

... Addition: Sorry I didn't join the discussion earlier, didn't  
makeit. But I hope you can make it to the workshop, as early adapter  
you'd be a great value

Best
Peggy


Quoting Peggy Yvonne Sylopp <syp@idmt.fraunhofer.de>:

> Hi
>
> create an accound at Jupyter notebook and fork the ai-project to  
> evaluate the log file:
> https://notebooks.ai/peggy/liketohear-ai-f671d451
>
> If you have problems, I recommend to join my workshop April 4th in Berlin:
> https://www.eventbrite.de/e/liketohear-workshop-for-open-source-hearing-devices-tickets-98613873751
>
> Good luck, have fun
> Peggy
>
>
> Quoting Hhz <notifications@github.com>:
>
>> Example entry:
>>
>> {"msg": "# RMS level in dB\n# vector<float> (monitor)\n[8.61453152  
>> 8.17349434 8.40927029 13.718174 12.8025684 21.3251095 10.7581635  
>> 8.51107693 11.8325844 12.006958 13.2003031  
>> 19.5938225]\n(MHA:success)\n", "userid": "abc", "data": [], "date":  
>> "Sun Mar  8 10:28:01 2020"}
>>
>> --
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/liketohear/liketohear/issues/9
>
>
> -- 
> Dipl. Inf. Peggy Yvonne Sylopp
>
> Citizen Science Project Manager "Hear How You Like To Hear"
>
> https://twitter.com/like_to_hear
> https://www.instagram.com/liketohear/
> https://www.facebook.com/Like_to_hear
>
> Fraunhofer Institute for Digital Media Technology IDMT
> Project Group Hearing, Speech and Audio Technology
> Haus des Hörens
> Marie-Curie-Strasse 2
> 26129 Oldenburg, Germany
>
> Tel.    +49 441 2172 433
> Mobile  +49 157 5360 1070


-- 
Dipl. Inf. Peggy Yvonne Sylopp

Citizen Science Project Manager "Hear How You Like To Hear"

https://twitter.com/like_to_hear
https://www.instagram.com/liketohear/
https://www.facebook.com/Like_to_hear

Fraunhofer Institute for Digital Media Technology IDMT
Project Group Hearing, Speech and Audio Technology
Haus des Hörens
Marie-Curie-Strasse 2
26129 Oldenburg, Germany

Tel.    +49 441 2172 433
Mobile  +49 157 5360 1070
